### ISSUE TITLE
docker-compose issue due to start timing

### ISSUE THREAD

**Issue by sguilly** [mijime/docker-mattermost#14]
Hi,

First, Thanks for your works.

When i use a docker-compose file, sometimes the mysql container is more slower to start than the mattermost container and the mattermost server exist...

Could be fine if we could specify a small delay with a environnement var before start mattermost ?

Stéphane

**Comment by mijime** [comment]
:tada: Thank you for using this container.

:laughing: Add option `MATTERMOST_START_DELAY`. The unit is in seconds.

**Comment by sguilly** [comment]
A big thank
