### ISSUE TITLE
Sign Up/Sign In with GitLab+HTTPS doesn't work

### ISSUE THREAD

**Issue by frol** [mijime/docker-mattermost#15]
I'm getting the following error message when try to sign into my GitLab:

"Token request failed"

The URL contains the following hint:

"Post https://my-mattermost-chat/gitlab/oauth/token/  x509 failed to load system roots and no roots provided"

Your image used to work fine with 3.1.0 version. I think it is related to glibc and possibly missing `ca-certificates`.

I was pleased to see that you use `frolvlad/alpine-glibc` image, but it is generally better to avoid Glibc on Alpine. Why have you chosen to switch from compiling from sources targeting musl libc to using pre-packaged binaries?

**Comment by mijime** [comment]
Thanks, try use my image.

> Why have you chosen to switch from compiling from sources targeting musl libc to using pre-packaged binaries?

I try `make build`. But failed.. from `image-webpack-loader`.
image-webpack-loader use https://github.com/imagemin/optipng-bin/tree/master/vendor/linux/x64.
I see optipng-bin need glibc ... ?

OK, I try compile one more ! 

Memo
- Only frontend may be used from the precompiled, backend build from sources.
