### ISSUE TITLE
Support for Mattermost Enterprise

### ISSUE THREAD

**Issue by sc250024** [mijime/docker-mattermost#24]
Greetings,

Currently the `Dockerfile` in the repo downloads the Team Edition of Mattermost at line 14: https://github.com/mijime/docker-mattermost/blob/master/Dockerfile#L14

At my organization we run the enterprise version of Mattermost, and it would be nice to be able to pull the image from Docker Hub that's been built for enterprise. Currently we do something like:

```
FROM mijime/mattermost:3.8.2

<DO OUR CUSTOM STUFF>
```

I've added this PR (https://github.com/mijime/docker-mattermost/pull/23) so that people might be able to pull from the Enterprise base image directly like so:

```
FROM mijime/mattermost-enterprise:3.8.2

<DO OUR CUSTOM STUFF>
```

I'm sure there is a better way to handle this without being repetitive; just throwing out the easiest solution.

**Comment by mijime** [comment]
Thanks, PR 🐳 

This image is currently being built from Github's source code.

Since the enterprise version code is not published, it seems that only static resources become enterprise version.

I think it would be better to extend for another image.
Example, https://github.com/s7b4/docker-mattermost

So, merging is a bit difficult. Sorry 🙇

**Comment by sc250024** [comment]
Would is be possible to have a base Mattermost image, and then add the Team or Enterprise tarball afterwards?

**Comment by sc250024** [comment]
@mijime: For example, the official Piwik repo has two flavors as well: https://github.com/piwik/docker-piwik

They use a `Dockerfile.template` at the root of the repo, and then have the `fpm` and `apache` versions. For this repo, it could be:
`mijime/mattermost:3.8.2-team` and `mijime/mattermost:3.8.2-enterprise`. You could still keep one repository.
