### ISSUE TITLE
4.1.0 release

### ISSUE THREAD

**Issue by frol** [mijime/docker-mattermost#27]
Could you, please, add 4.1.0 release?

P.S. 4.2.0 is coming...

**Comment by frol** [comment]
@mijime Thank you!

P.S. 4.0 tag on Docker Hub is getting rebuilt as well. Is this expected?

**Comment by mijime** [comment]
Thank you tell me!
4.0 build is not expected...  I tried cancel.

**Comment by mijime** [comment]
I made a mistake. I am updating to 4.0.4.

**Comment by frol** [comment]
Just for your info, 4.1.0 (`latest` tag) works fine for me! Thanks
