### ISSUE TITLE
bump to version 2.1.0

### ISSUE THREAD

**Issue by legoheld** [mijime/docker-mattermost#3]
@mijime Do you have the time to bump to version 2.1.0 or should create a pull request?

**Comment by mijime** [comment]
Thank you for letting me notice. PR are accepted at any time!

**Comment by legoheld** [comment]
Your welcome. If you have time to bump the version I really appreciate as I have no local setup and it would be the first time I would do something like that. But if you don't have the time I would invest the time.
By the way your image is much clearer with the db separation and the config generation than the official one. Thank you.

**Comment by mijime** [comment]
https://hub.docker.com/r/mijime/mattermost/tags/
Once it has been upgraded! We will continue to modify from now to accept the 2.1.0 configuration.
Please wait a little more time!

If you try, please run  `docker pull mijime/mattermost:2.1.0`

**Comment by mijime** [comment]
:bow: Once close. Also please contact feel free to if there are any problems.

**Comment by legoheld** [comment]
Very well! Thank you for your quick help! :pray:
